### ISSUE TITLE
Unable to check emails in inbox

### ISSUE THREAD

**Issue by tashan022** [HanzHaxors/DisposableEmailCLI#1]
```
Email address: T3608@1secmail.com
+----------+--------------------+--------------------------------------------+---------------------+
|    id    |        From        |                  Subject                   |         Date        |
+----------+--------------------+--------------------------------------------+---------------------+
| 13397623 | noreply@github.com | [GitHub] Please verify your email address. | 2020-01-05 14:43:18 |
+----------+--------------------+--------------------------------------------+---------------------+
[+] Message id to read (r to refresh inbox): 13397623
Traceback (most recent call last):
  File "emailinbox.py", line 122, in <module>
    initme()
  File "emailinbox.py", line 118, in initme
    tableTheInbox(log, dom)
  File "emailinbox.py", line 80, in tableTheInbox
    tableTheInbox(login, domain)
  File "emailinbox.py", line 82, in tableTheInbox
    goRead(str(inp), login, domain)
  File "emailinbox.py", line 57, in goRead
    theRes = message(login, domain, id)
  File "D:\IUSER\Documents\Downloads\DisposableEmailCLI-master\secmail\api.py", line 13, in message
    resjson = loads(get('https://www.1secmail.com/api/v1/?action=readMessages&login='+login+'&domain='+domain+'&id='+id).text)
  File "C:\Users\IUSER\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\IUSER\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\IUSER\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise IUSER("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (cha
```r 0)

**Comment by HanzHaxors** [comment]
I will recheck the 1secmail api... please wait 😅

**Comment by HanzHaxors** [comment]
We made it! i'll give you credit 😄

**Comment by HanzCEO** [comment]
What have i done? huh interesting young me
